### ISSUE TITLE
atomic radii in addwater.py

### ISSUE THREAD

**Issue by ghost** [akshay-sridhar/WaterDock2.0#1]
@akshay-sridhar 

I am trying to run WaterDock2.0 on some ligands with atoms that are not defined in the addwater.py script (lines 78-88). 

Where did you get the atomic radii from? I would like to add some more atoms into my local copy of the script.

Thanks,

Susan

**Comment by akshay-sridhar** [comment]
Hello Susan,
Thank you for trying WaterDock. 

The atomic radii were adopted from the values used in the development of Antechamber module of Amber. See the parameter values in Table 6 at http://ambermd.org/antechamber/antechamber.pdf

Out of curiosity, may I enquire the atom you wanted to add? I could add it to the main WaterDock code too. 

Thanks,
Akshay

**Comment by ghost** [comment]
Thank you very much Akshay.

I would like to add boron and iodine. 

If you could add to the main WaterDock code, that would be very useful and I am sure others would find it beneficial too. 

Thanks!
Susan
